#======================================
#**************************************
#
# Octavia Shaw -- Pentagonal numbers
#
# Project Euler -- Ruby Practice
#
# Find the pair of pentagonal numbers, Pj and Pk, for which their sum and 
# difference are pentagonal and D = |Pk − Pj| is minimised; what is the value 
# of D?
#
#**************************************
#======================================


# STRATEGY 
# since the distance (D = |P_k - P_j|) between pentagonal numbers increases as 
# k and j increase due to the nature of the series the first pair of pentagonal
# numbers such that P_k + P_j is pentagonal and P_k - P_j is pentagonal will 
# have the minimal distance. Therefore we create a loops

# Accepts an integer>0 and determines whether or not is is a pentagonal number
# Returns true or false
def is_pentnum?(n)
	n = (math.sqrt(24*n + 1) + 1 ) / 6.0
	return true if n % 1==0 else return false
end

# Accepts an integer>0 and returns the pentagonal number generated by formula 
# p_n = n(3n-1)/2
def pentnum(n)
	return n*(3*n - 1)/2
end

#
#
